Ready for Swift 6 blog post
swiftlang/swift-org-website pull request #734
Opened 2024-06-19 08:24 UTC by daveverwer

![Screenshot 2024-06-19 at 09 21 43@2x](https://github.com/swiftlang/swift-org-website/assets/5180/f58cf291-e7fe-4866-9299-d73410ea5e03)

2024-06-20 06:17 UTC, alexandersandberg reviewed
👏

Left some smaller comments. 🙂

2024-06-20 06:17 UTC, alexandersandberg commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index’s new “[Ready for Swift 6](https://swiftpackageindex.com/ready-for-swift-6)”  page tracks progress toward data race safety across the entire package ecosystem. While packages
```suggestion
The Swift Package Index’s new “[Ready for Swift 6](https://swiftpackageindex.com/ready-for-swift-6)” page tracks progress toward data race safety across the entire package ecosystem. While packages can opt-in to Swift 6 language mode at their convenience, this page shows the number of packages that would pass those checks if all strict concurrency checks were enabled for all packages.
```

2024-06-20 06:17 UTC, alexandersandberg commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
```suggestion
The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://swiftpackageindex.com/ready-for-swift-6#total-zero-errors). Then, for the past week since the first beta version of Xcode 16 was unveiled the Swift Package Index build machines have been running fresh builds with the advantage of platform SDKs that have more Sendable conformance, bringing the total percentage of packages with zero data race errors to over 43%! That's a really great start for being only one week into the Xcode 16 beta process.
```

2024-06-20 06:17 UTC, alexandersandberg commented on _posts/2024-06-20-ready-for-swift-6.md
> +While packages can opt-in to Swift 6 language mode at their convenience, the chart shows the number of packages that would pass those checks if all strict concurrency checks were explicitly enabled f
This line is very similar to the one on [line 13](https://github.com/swiftlang/swift-org-website/pull/734/files#diff-1f74d4e276a408a0d8dbf0732e7ebd6d6f4da648a46ba728b0142730a8fab036R13). Maybe we can rewrite/remove one of them?

>While packages can opt-in to Swift 6 language mode at their convenience, this page shows the number of packages that would pass those checks if all strict concurrency checks were enabled for all packages.

>While packages can opt-in to Swift 6 language mode at their convenience, the chart shows the number of packages that would pass those checks if all strict concurrency checks were explicitly enabled for a package.

2024-06-20 06:17 UTC, alexandersandberg commented on _posts/2024-06-20-ready-for-swift-6.md
> +When evaluating a package, it is be helpful to know if that package has any reported data race safety issues. To assist with this, the Swift Package Index now displays a “Safe from data races” label
```suggestion
When evaluating a package, it is helpful to know if that package has any reported data race safety issues. To assist with this, the Swift Package Index now displays a “Safe from data races” label alongside other package metadata when packages compile with zero errors using `complete` strict concurrency checks.
```

2024-06-20 06:25 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +While packages can opt-in to Swift 6 language mode at their convenience, the chart shows the number of packages that would pass those checks if all strict concurrency checks were explicitly enabled f
Well spotted. I think that second sentence adds nothing, I'll remove that one.

2024-06-20 06:30 UTC, daveverwer commented
> 👏
> 
> Left some smaller comments. 🙂

Thanks for the review @alexandersandberg!

2024-06-25 15:20 UTC, finagolfin commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index’s new “[Ready for Swift 6](https://swiftpackageindex.com/ready-for-swift-6)” page tracks progress toward data race safety across the entire package ecosystem. While packages c
opt-in -> opt in

2024-06-25 15:22 UTC, finagolfin commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
unveiled the -> unveiled, the

2024-06-25 15:27 UTC, finagolfin approved these changes
Great effort to highlight this feature on SPI, just found a couple grammar errors in the post.

2024-06-25 15:41 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
Thanks! Fixed

2024-06-25 15:41 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index’s new “[Ready for Swift 6](https://swiftpackageindex.com/ready-for-swift-6)” page tracks progress toward data race safety across the entire package ecosystem. While packages c
Thanks! Fixed

2024-06-25 15:44 UTC, daveverwer commented
@swift-ci please test

2024-06-26 18:41 UTC, timsneath requested changes
Looking great. Some suggestions and review comments attached.

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +Swift 6 introduces compile-time data race safety checking for any code that [opts in to use the Swift 6 language mode](https://www.swift.org/migration/documentation/swift-6-concurrency-migration-guid
It would be great to link "compile-time data race safety checking" to https://www.swift.org/migration/documentation/swift-6-concurrency-migration-guide/dataracesafety so that there's an easy way to get more information about what this means.

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +Swift 6 introduces compile-time data race safety checking for any code that [opts in to use the Swift 6 language mode](https://www.swift.org/migration/documentation/swift-6-concurrency-migration-guid
Suggest some minor tweaks to emphasize that partial adoption is of value and avoid giving any sense that this is existential for the success of Swift.
```suggestion
Swift 6 introduces compile-time data race safety checking for any code that [opts in to use the Swift 6 language mode](https://www.swift.org/migration/documentation/swift-6-concurrency-migration-guide/swift6mode). While individual modules can adopt this mode incrementally and independently of their dependencies, the full benefit of runtime data race safety is only realized when all modules have opted in. Therefore, the quick adoption of Swift 6 language mode across the ecosystem of open-source packages will play a key role in advancing data race safety across the entire Swift ecosystem.
```

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
```suggestion
The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and there's already a steady reduction in the [number of packages with data race errors](https://swiftpackageindex.com/ready-for-swift-6#total-zero-errors). Then, for the past week since the first beta version of Xcode 16 was unveiled, the Swift Package Index build machines have been running fresh builds with the advantage of platform SDKs that have more `Sendable` conformance, bringing the total percentage of packages with zero data race errors to over 43%! That's a really great start for being only one week into the Xcode 16 beta process.
```

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
We probably shouldn't bring Xcode into the equation here -- this article is about Swift 6. Xcode happens to deploy an updated Swift toolchain, but the IDE itself doesn't do anything Swift-related, does it?

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
I'm finding it hard to connect the data point here (43% zero data race errors) to the chart above. Is there a version of the chart that could show this percentage trend explicitly?

I'm also a bit confused by what we're communicating here? Are the 57% with zero data race errors packages that have not adopted Swift 6? Or packages that have adopted Swift 6 but have more work to do in later betas?

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +Over time, successful adoption of Swift 6 language mode in the package ecosystem will come from two directions. First, as more packages opt into these checks, package authors will fix potential data
What is the nature of the "refinement" in improved accuracy in the last sentence? Improving accuracy? Reducing false positives? Or something else?

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +When evaluating a package, it is helpful to know if that package has any reported data race safety issues. To assist with this, the Swift Package Index now displays a “Safe from data races” label alo
Recommend link to https://www.swift.org/migration/documentation/swift-6-concurrency-migration-guide/completechecking to show developers how they can turn on this mode.

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +During the transition to Swift 6, you will likely see packages that show a green tick against Swift 6 in Swift Package Index’s platform and Swift version compatibility matrix while also showing that
Finish the thought here: what does that mean? Can the package be used from a project that has strict concurrency mode enabled? Is this a cause for concern that suggests the package is unstable and may crash? Or is the package still fine for adoption? 

Out of curiosity -- should we not have a different symbol for these packages? A yellow symbol? Or a lighter green checkmark?

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +During the transition to Swift 6, you will likely see packages that show a green tick against Swift 6 in Swift Package Index’s platform and Swift version compatibility matrix while also showing that
American English is "checkmark", not "tick". I believe we standardize on US English for the blog, and the latter may not be so well understood by a broad audience.

2024-06-26 18:41 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +Data race safety is a crucial feature of the Swift 6 compiler, eliminating many subtle or significant issues. For this feature to be effective, widespread adoption is essential. We urge package autho
Updating this language to draw from our carefully-honed State of the Union messaging!

```suggestion
Compile-time data race safety is a major advance for the Swift language, eliminating an entire class of potential concurrency bugs and elevating your code's safety and maintainability. Every module that migrates to Swift 6 contributes to the community-wide transition to bring data race safety to the Swift software ecosystem. You can help by [updating your own packages](https://www.swift.org/migration/), and you can follow the broader ecosystem's progress on the [Ready for Swift 6 page on the Swift Package Index](https://swiftpackageindex.com/ready-for-swift-6).
```

2024-06-26 18:50 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
You're correct, but I wanted to mark the occasion of it being the first Swift 6 version that shipped to a wider audience than those developers who would grab a nightly version. We could mention the toolchain date (although I'm not 100% sure how to find that for the version that ships in Xcode).

2024-06-26 18:53 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
We could just make this a little more vague and say "Then, for the past week, the Swift Package Index build machines have been running fresh builds with the advantage of platform SDKs that have more Sendable conformance"

Removing "since the first beta version of Xcode 16 was unveiled" altogether.

2024-06-26 19:00 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
I believe the percentage is correct, as shown by the tooltips below, but you're correct that we don't explicitly state the percentage in the data point tooltip.

![Screenshot 2024-06-26 at 19 55 39@2x](https://github.com/swiftlang/swift-org-website/assets/5180/62e35303-dda9-41e8-996a-59a04d846a56)

If I were able to add that percentage to the tooltip, would that make this clearer?

2024-06-26 19:04 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
> I'm also a bit confused by what we're communicating here? Are the 57% with zero data race errors packages that have not adopted Swift 6? Or packages that have adopted Swift 6 but have more work to do in later betas?

I agree this is a little confusing. This chart plots the status of packages as if they had been "forced" to adopt Swift 6 language mode and "complete" concurrency checking. It does not show how many packages have voluntarily opted in. We do explain this in FAQ question 2 below the chart, but we could potentially be clearer about that. I'll work on a revised version of the FAQ question.

2024-06-26 19:12 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +Swift 6 introduces compile-time data race safety checking for any code that [opts in to use the Swift 6 language mode](https://www.swift.org/migration/documentation/swift-6-concurrency-migration-guid
Link added. Thanks!

2024-06-26 19:18 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +When evaluating a package, it is helpful to know if that package has any reported data race safety issues. To assist with this, the Swift Package Index now displays a “Safe from data races” label alo
Added a link here:

![Screenshot 2024-06-26 at 20 18 00@2x](https://github.com/swiftlang/swift-org-website/assets/5180/c063dbe5-46a3-4f72-86d7-0e4b298fcac4)

2024-06-26 19:21 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +During the transition to Swift 6, you will likely see packages that show a green tick against Swift 6 in Swift Package Index’s platform and Swift version compatibility matrix while also showing that
Good catch! 🇬🇧 Fixed

2024-06-26 19:40 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
> If I were able to add that percentage to the tooltip, would that make this clearer?

I wonder if the chart just needs inverting. Perhaps it's more natural to show "% of packages with data race errors" and show that the number is trending to 0%?

2024-06-26 19:42 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
That could work, or you could just be more explicit and say, "with the first developer betas of Xcode 16, Swift 6 is now available to a much wider audience. And..."

2024-06-26 19:44 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
> This chart plots the status of packages as if they had been "forced" to adopt Swift 6 language mode and "complete" concurrency checking.

I'd just say that -- I think that's helpful context!

2024-06-26 19:45 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
I just reworked this paragraph a little to remove both mentions of Xcode and refer to it as "The Swift 6 beta process"

![Screenshot 2024-06-26 at 20 44 33@2x](https://github.com/swiftlang/swift-org-website/assets/5180/7956dd67-b73d-4eb1-9f26-8abea7d37434)

2024-06-26 19:51 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +When evaluating a package, it is helpful to know if that package has any reported data race safety issues. To assist with this, the Swift Package Index now displays a “Safe from data races” label alo
> Great -- or just link the "complete strict concurrency checks" text to the URL, which will help with SEO!

Changed to this suggestion instead.

2024-06-28 07:46 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and you can already see the [number of packages without data race errors increasing](https://sw
I have updated the FAQ on the SPI Ready for Swift 6 page to include wording similar to this.

![Screenshot 2024-06-28 at 08 45 55@2x](https://github.com/swiftlang/swift-org-website/assets/5180/649cdd0f-0749-431f-b45e-cb6eadb4e39e)

2024-06-28 08:34 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +During the transition to Swift 6, you will likely see packages that show a green tick against Swift 6 in Swift Package Index’s platform and Swift version compatibility matrix while also showing that
> Finish the thought here: what does that mean? Can the package be used from a project that has strict concurrency mode enabled? Is this a cause for concern that suggests the package is unstable and may crash? Or is the package still fine for adoption?

This made me realise I haven’t actually said what problems data races cause, so I added a sentence at the top of the article to cover that. I also covered whether the package can be used at the end of this section.

> Out of curiosity -- should we not have a different symbol for these packages? A yellow symbol? Or a lighter green checkmark?

I don’t think we should do this. The compatibility matrix has a clear job, and that is to report compatibility at a glance. Whether someone wants to use a package is based on lots of metadata in the above section, with data race safety being part of that, and compatibility being another part. We shouldn’t try to represent any other metadata with the compatibility information.

2024-06-28 08:56 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +Over time, successful adoption of Swift 6 language mode in the package ecosystem will come from two directions. First, as more packages opt into these checks, package authors will fix potential data
As I understand it, there are still some proposals in active review (like [SE-0430](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0430-transferring-parameters-and-results.md)) that will affect and potentially reduce the number of warnings/errors. I don’t know the exact status of all the other evolution proposals that are accepted, but it’s possible some are not yet in the compiler that shipped with beta1 or beta2. I don’t know, so I was intentionally a little vague here, but I know more is being done by Apple.

2024-06-28 08:57 UTC, daveverwer commented
Thank you for the very comprehensive review, @timsneath. I think it's ready for a final review now.

2024-06-28 17:27 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +Over time, successful adoption of Swift 6 language mode in the package ecosystem will come from two directions. First, as more packages opt into these checks, package authors will fix potential data
OK, vague is fine then. Thanks!

2024-06-28 17:29 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +During the transition to Swift 6, you will likely see packages that show a green tick against Swift 6 in Swift Package Index’s platform and Swift version compatibility matrix while also showing that
OK, sounds good! 

Unrelated to this thread, we saw good success with using scores to incentivize best practices for Flutter; see for example, https://pub.dev/packages/path_provider/score. Might be something to consider in the future for Swift Package Index?

2024-06-28 17:30 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and there has already been a steady reduction in the [number of packages with data race errors]
Need a space here:
> over 43%!That's

2024-06-28 17:31 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index’s new “[Ready for Swift 6](https://swiftpackageindex.com/ready-for-swift-6)” page tracks progress toward data race safety across the entire package ecosystem. While packages c
Do we need quotes around "Ready for Swift 6"? Consider removing.

2024-06-28 17:32 UTC, timsneath approved these changes

2024-06-28 17:50 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index has been running these checks using Swift 6 nightly toolchains since early May, and there has already been a steady reduction in the [number of packages with data race errors]
Fixed. Thanks!

2024-06-28 17:50 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +The Swift Package Index’s new “[Ready for Swift 6](https://swiftpackageindex.com/ready-for-swift-6)” page tracks progress toward data race safety across the entire package ecosystem. While packages c
Removed. Thanks!

2024-06-28 17:53 UTC, daveverwer commented
@swift-ci please test

2024-06-28 17:58 UTC, daveverwer commented
Thanks everyone! I think this one is ready to go. The date is currently set to today but I can update it as the last change when we have a publish date.

2024-06-28 18:21 UTC, daveverwer commented
@swift-ci please test

2024-06-28 18:25 UTC, daveverwer commented on _posts/2024-06-20-ready-for-swift-6.md
> +During the transition to Swift 6, you will likely see packages that show a green tick against Swift 6 in Swift Package Index’s platform and Swift version compatibility matrix while also showing that
We have some work in this area but are deliberately not pushing it prominently yet as we did get a little push back when we implemented some of the metrics, and there are not enough yet to make it comprehensive. You can see the work we did on any "maintainer's" page, like this:

https://swiftpackageindex.com/SwiftPackageIndex/SemanticVersion/information-for-package-maintainers#package-score

I'd love to pick your brains sometime about how this worked for Flutter and how you rolled it out with the community.

![Screenshot 2024-06-28 at 19 24 03@2x](https://github.com/swiftlang/swift-org-website/assets/5180/304256cd-f504-4074-ac8f-bbcbe0d6e0fc)

2024-06-28 18:37 UTC, timsneath commented on _posts/2024-06-20-ready-for-swift-6.md
> +During the transition to Swift 6, you will likely see packages that show a green tick against Swift 6 in Swift Package Index’s platform and Swift version compatibility matrix while also showing that
Cool -- yeah, let's schedule some time to talk about this. I'll add some comments to https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/2591

2024-07-01 13:16 UTC, daveverwer commented
@swift-ci please test

2024-07-01 15:43 UTC, merged