Windows: add ARM64 MSVC Tools to VS installation
swiftlang/swift-org-website pull request #843
Opened 2024-11-05 19:14 UTC by compnerd

Instruct users to install the MSVC ARM64 tools when installing Visual Studio. This should ensure that cross-compilation is possible (and native compilation when on ARM64).

Fixes: #839

2024-11-05 19:25 UTC, cthielen commented
If this component is optional and only needed for cross-compilation, I recommend including that detail in the instructions to avoid asking folks to download extra components.

2024-11-05 19:26 UTC, timsneath commented
I hear what you're saying, @cthielen. I wonder if we might be OK here though -- since this is just a copy and paste command? The trade-off is that if we over-explain, we add friction to the process...

2024-11-05 19:27 UTC, timsneath commented on install/windows/_winget.md
> +   winget install --id Microsoft.VisualStudio.2022.Community --exact --force --custom "--add Microsoft.VisualStudio.Component.Windows11SDK.22000 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x6
This doesn't look right -- you have the same component listed twice:
```
Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.VC.Tools.x86.x64
```

2024-11-05 19:28 UTC, timsneath requested changes
See comment above...

2024-11-06 13:54 UTC, bkhouri requested changes
Issue (blocking): Can we also update the Scoop installation instructions to install the ARM64 tools?

I assume this may be the required changes, but I have not tested it.
```
diff --git a/install/windows/_scoop.md b/install/windows/_scoop.md
index 2ea5b7f4..ed033939 100644
--- a/install/windows/_scoop.md
+++ b/install/windows/_scoop.md
@@ -26,7 +26,7 @@ Invoke-RestMethod get.scoop.sh | Invoke-Expression
 
    ~~~ batch
    curl -sOL https://aka.ms/vs/17/release/vs_community.exe
-   start /w vs_community.exe --passive --wait --norestart --nocache --add Microsoft.VisualStudio.Component.Windows11SDK.22000 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
+   start /w vs_community.exe --passive --wait --norestart --nocache --add Microsoft.VisualStudio.Component.Windows11SDK.22000 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.ARM64
    del /q vs_community.exe
    ~~~
 
diff --git a/install/windows/scoop/index.md b/install/windows/scoop/index.md
index 5a7fde42..0d7ba13c 100644
--- a/install/windows/scoop/index.md
+++ b/install/windows/scoop/index.md
@@ -29,7 +29,7 @@ Invoke-RestMethod get.scoop.sh | Invoke-Expression
 
    ~~~ batch
    curl -sOL https://aka.ms/vs/17/release/vs_community.exe
-   start /w vs_community.exe --passive --wait --norestart --nocache --add Microsoft.VisualStudio.Component.Windows11SDK.22000 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
+   start /w vs_community.exe --passive --wait --norestart --nocache --add Microsoft.VisualStudio.Component.Windows11SDK.22000 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.ARM64
    del /q vs_community.exe
    ~~~
```

2024-11-06 16:59 UTC, bkhouri approved these changes

2024-11-06 16:59 UTC, compnerd commented
@swift-ci please test

2024-11-06 17:06 UTC, timsneath approved these changes

2024-11-06 17:16 UTC, timsneath commented
@swift-ci please test

2024-11-06 17:17 UTC, merged